// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Foundation;
using NewTemperatureApp3.Helper;
using NewTemperatureApp4.Model;
using Newtonsoft.Json;
using UIKit;

namespace NewTemperatureApp4
{
	public partial class SecondViewController : UIViewController
	{
        public List<String> allList = new List<String>();
        public List<String> allListHumidity = new List<String>();
        public SecondViewController (IntPtr handle) : base (handle)
		{
		}

        public override async void ViewDidLoad()
        {
            base.ViewDidLoad();
            await GetForecastInfo();
            TableView.ReloadData();
            TableView.Source = new MyTableViewSource(allListHumidity);
        }

        async Task GetForecastInfo(string Location = "Mumbai")
        {
            var url = $"https://api.openweathermap.org/data/2.5/forecast?q=Mumbai&appid=c73297b9b55ee7d91152ab5a16dcd324";
            var result = await ApiCaller.Get(url);
            var forecastInfo = JsonConvert.DeserializeObject<ForecastInfo>(result.Response);
            var x = forecastInfo.list;
            foreach (var j in x)
            {
                var y = j.main.temp.ToString();
                allList.Add(y);
            }
            foreach (var j in x)
            {
                var y = j.main.humidity.ToString();
                allListHumidity.Add(y);
            }
        }

       
    }
}
